server:
  port: 8000

logging.level.com.smockin: INFO

jpa:
  show-sql: false
  hibernate:
    ddl-auto: create-drop
datasource:
  url: jdbc:h2:mem:smockindev
  driver-class-name: org.h2.Driver
  username: sa
  password:

smockin:
  ftp.root.dir: "${user.home}/.smockin/ftp/"
  auth.exclusions: '{"*.html":["GET"],"*.js":["GET"],"*.css":["GET"],"*.woff2":["GET"],"*.png":["GET"],"*.gif":["GET"],"/auth":["POST"],"/user/mode":["GET"],"/mockedserver/rest/status":["GET"],"/mockedserver/jms/status":["GET"],"/mockedserver/ftp/status":["GET"],"/password/reset/token/*":["GET","POST"]}'




# TRACING-settings
opentracing:
  jaeger:
    service-name: AppB
    enabled: TRUE
    udp-sender:
      host: jaeger-agent         
            
            


---
# NOTE
# The 'start.sh' script overrides the below DB related params using values defined
# in the DB config file: '$USER_HOME/.smockin/db/db.properties'.
spring:
  application:
    name: smockin
  profiles:
    active: production
  cloud:
   compatibility-verifier: 
     enabled: false
  sleuth:
      opentracing:
           enabled: true    
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:/app/smockinDB
    driver-class-name:
    username:
    password:
    maximumPoolSize: 10
    hikari:
      poolName: smockinpool
      idle-timeout: 10000